### ISSUE TITLE
search on demo app does not work

### ISSUE THREAD

**Issue by growandwin** [ember-learn/super-rentals#155] opened 2021-01-15 15:42 UTC
Hi, I visited https://ember-super-rentals.netlify.app/ and tried search - no matter what I write, the result list becomes empty

**Comment by ijlee2** [comment] 2021-01-15 15:50
Hi, @growandwin. Can you tell us more about what you typed in for search?

There are 3 rental properties and I was able to filter them by typing a letter. I did notice that filtering is case-sensitive. Perhaps that could be why?

**Comment by rajasegar** [comment] 2021-02-16 04:48
The search is case-sensitive and from the first character of the names, so you should try with something like `Grand`, `Urban`, `Down`

**Comment by ijlee2** [comment] 2021-03-04 07:42
Closing this issue since the search was working as intended.

**Closed by ijlee2** 2021-03-04 07:42 UTC
